# Generated by Django 4.1 on 2022-09-12 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 12, 17, 54, 29, 736597)),
        ),
    ]
