# Generated by Django 4.1 on 2022-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ELSE.', 'Else'), ('ACCESORIES', 'Accessories'), ('SPORT', 'Sports'), ('CLOTHING', 'Clothing'), ('ELECTRONICS', 'Electronics'), ('ART', 'Art'), ('MOVIES-AND-TV', 'Movies and Television'), ('TOYS-AND-GAMES', 'Toys and Games'), ('VIDEO-GAMES', 'Video Games'), ('HOME-AND-KITCHEN', 'Home and Kitchen'), ('SELF-CARE', 'Self Care'), ('BOOKS', 'Books')], default='ELSE.', max_length=30),
        ),
    ]
