# Generated by Django 4.1 on 2022-09-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='price',
        ),
    ]
