# Generated by Django 4.1 on 2022-09-12 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 9, 12, 18, 10, 30, 357998)),
        ),
    ]
