# Generated by Django 4.1 on 2022-09-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ELSE.', 'Else'), ('ACCESORIES', 'Accessories'), ('SPORT', 'Sports'), ('CLOTHING', 'Clothing'), ('ELECTRONICS', 'Electronics'), ('ART', 'Art'), ('MOVIES-AND-TV', 'Movies and Television'), ('TOYS-AND-GAMES', 'Toys and Games'), ('VIDEO-GAMES', 'Video Games'), ('HOME-AND-KITCHEN', 'Home and Kitchen'), ('SELF-CARE', 'Self Care'), ('BOOKS', 'Books')], default='ELSE.', max_length=30)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(to='auctions.category'),
        ),
    ]
